readme update
tidev/pulsar-titanium pull request #670
Opened 2023-03-01 18:52 UTC by m1ga

* Atom -> Pulsar
* Appcelerator -> :cloud:

2023-03-02 21:40 UTC, ewanharris requested changes
Just some comments, but this is ace thanks!

2023-03-02 21:40 UTC, ewanharris commented on README.md
> +ppm install https://github.com/tidev/pulsar-titanium
I think they're leaning towards `pulsar --package` now over `ppm` (and I've had issues with it on Windows)
```suggestion
pulsar --package install https://github.com/tidev/pulsar-titanium
```

2023-03-02 21:40 UTC, ewanharris commented on README.md
> +ppm install pulsar-titanium
```suggestion
pulsar --package install pulsar-titanium
```

2023-03-02 21:40 UTC, ewanharris commented on README.md
> +* Install `pulsar-titanium` package.
Package name is just `titanium`, I think we do still need some extra packages but I'll need to check what else is needed

```suggestion
* Install `titanium` package.
```

2023-03-02 21:40 UTC, ewanharris commented on README.md
> +Preferences/Settings > Install > Search for `pulsar-titanium`.
Package name is just titanium

```suggestion
Preferences/Settings > Install > Search for `titanium`.
```

2023-03-02 21:40 UTC, ewanharris commented on README.md
> +The build select button executes and provides selections of the build command. Depending on the target platform selected, the drop-down will display options for the `ti run` command:
```suggestion
The build select button executes and provides selections of the build command. Depending on the target platform selected, the drop-down will display options for the `ti build` command:
```

2023-03-02 21:40 UTC, ewanharris commented on README.md
> +* Custom: Execute `ti run -d <project_dir>` with custom arguments
```suggestion
* Custom: Execute `ti build -d <project_dir>` with custom arguments
```

2023-03-02 21:40 UTC, ewanharris commented on README.md
> +The console displays debug logging during the build and run. The log level is passed to the `appc run` comand so selecting the log level does not alter output from the currently executing command. Th
```suggestion
The console displays debug logging during the build and run. The log level is passed to the `ti build` command so selecting the log level does not alter output from the currently executing command. There are options to automatically scroll the console to the latest message and to open it when a build is initiated.
```

2023-03-02 21:42 UTC, m1ga commented
thanks for the commit suggestions :+1: All valid of course!

2023-03-05 21:03 UTC, ewanharris approved these changes
Thanks @m1ga!

2023-03-05 21:03 UTC, merged